//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34003
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calendario_Estudiantil {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Calendario_Estudiantil.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actividad borrada.
        /// </summary>
        public static string ActBorrada {
            get {
                return ResourceManager.GetString("ActBorrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actividad guardada.
        /// </summary>
        public static string ActGuardada {
            get {
                return ResourceManager.GetString("ActGuardada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actividad.
        /// </summary>
        public static string Actividad {
            get {
                return ResourceManager.GetString("Actividad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actividades.
        /// </summary>
        public static string Actividades {
            get {
                return ResourceManager.GetString("Actividades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        public static string Agregar {
            get {
                return ResourceManager.GetString("Agregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar actividad.
        /// </summary>
        public static string AgregarAct {
            get {
                return ResourceManager.GetString("AgregarAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alarma.
        /// </summary>
        public static string Alarma {
            get {
                return ResourceManager.GetString("Alarma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El azul simboliza pruebas..
        /// </summary>
        public static string Azul {
            get {
                return ResourceManager.GetString("Azul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar actividad.
        /// </summary>
        public static string BorrarAct {
            get {
                return ResourceManager.GetString("BorrarAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comentario: .
        /// </summary>
        public static string Comentario {
            get {
                return ResourceManager.GetString("Comentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No registra detalles: .
        /// </summary>
        public static string ComentarioNo {
            get {
                return ResourceManager.GetString("ComentarioNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Control.
        /// </summary>
        public static string Control {
            get {
                return ResourceManager.GetString("Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lun.
        /// </summary>
        public static string dia1 {
            get {
                return ResourceManager.GetString("dia1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mar.
        /// </summary>
        public static string dia2 {
            get {
                return ResourceManager.GetString("dia2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mie.
        /// </summary>
        public static string dia3 {
            get {
                return ResourceManager.GetString("dia3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jue.
        /// </summary>
        public static string dia4 {
            get {
                return ResourceManager.GetString("dia4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vie.
        /// </summary>
        public static string dia5 {
            get {
                return ResourceManager.GetString("dia5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sab.
        /// </summary>
        public static string dia6 {
            get {
                return ResourceManager.GetString("dia6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dom.
        /// </summary>
        public static string dia7 {
            get {
                return ResourceManager.GetString("dia7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disertacion.
        /// </summary>
        public static string Disertacion {
            get {
                return ResourceManager.GetString("Disertacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha:.
        /// </summary>
        public static string Fecha {
            get {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hora:.
        /// </summary>
        public static string Hora {
            get {
                return ResourceManager.GetString("Hora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        public static string Idioma {
            get {
                return ResourceManager.GetString("Idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El marrón simboliza trabajos..
        /// </summary>
        public static string Marron {
            get {
                return ResourceManager.GetString("Marron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El naranjo simboliza controles..
        /// </summary>
        public static string Naranjo {
            get {
                return ResourceManager.GetString("Naranjo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No registra actividades..
        /// </summary>
        public static string NoRegistraAct {
            get {
                return ResourceManager.GetString("NoRegistraAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nota:.
        /// </summary>
        public static string Nota {
            get {
                return ResourceManager.GetString("Nota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prueba.
        /// </summary>
        public static string Prueba {
            get {
                return ResourceManager.GetString("Prueba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Simbología.
        /// </summary>
        public static string Simbología {
            get {
                return ResourceManager.GetString("Simbología", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo:.
        /// </summary>
        public static string Tipo {
            get {
                return ResourceManager.GetString("Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calendario Estudiantil.
        /// </summary>
        public static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trabajo.
        /// </summary>
        public static string Trabajo {
            get {
                return ResourceManager.GetString("Trabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver actividades.
        /// </summary>
        public static string VerAct {
            get {
                return ResourceManager.GetString("VerAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El verde simboliza disertaciones..
        /// </summary>
        public static string Verde {
            get {
                return ResourceManager.GetString("Verde", resourceCulture);
            }
        }
    }
}
